import type { Metadata } from "next";
import { Inter, Lexend } from "next/font/google";

import { MainLayout } from "@/src/shared/components/common/Layout";

import { ThemeProvider } from "next-themes";
import { AntdStyledComponentsRegistry } from "@/src/shared/infra/antd/AntdStyledComponentsRegistry";
import { ClerkProvider } from "@clerk/nextjs";

import "@/src/shared/styles/_main.scss";

const lexend = Lexend({ display: "swap", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <ClerkProvider>
          <ThemeProvider attribute="class">
            <AntdStyledComponentsRegistry>
              <MainLayout>{children}</MainLayout>
            </AntdStyledComponentsRegistry>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
